### ISSUE TITLE
Is there plan to be database agnostic by using ORM?

### ISSUE THREAD

**Issue by yihuang** [neocogent/sqlchain#6]
Does it depend on mysql inherently?

**Comment by neocogent** [comment]
I have no plans currently in that direction. I have only a very passing familiarity with things like SQLAlchemy or Django and don't use either for any work I do. If you have ideas about how to do it or why it would be great then I'm open.

Right now the code has only been tested with MySQL. It's probably not hard to abstract it a bit so it could work with Postgresql. I know a lot of people use that and like it better. I only went this way because it's what I'm familiar with. I hopefully didn't do anything that ties it to MySQL. The sql statements may need to be tweaked to be a bit more generic. I have not even looked at that. I have tested with several engines under MySQL (myisam, rocksdb, tokudb) and did make some changes to make it work better in a more transactional environment (commits). 

My intent was never for it to be the base for an enterprise db system but rather to try and minimize storage requirements. I was looking for a way to use the bitcoin blockchain on lower end hardware (vps) rather than something that may be more suited to large projects. It works well for what I wanted but it does have some oddities that probably would have been avoided if resources were less constrained.

When I started the blockchain was 60GB and other blockchain-sql options typically needed 300GB due to many index and "proper" bloated schemas. They probably need over 1TB nowadays, though I haven't checked. sqlchain actually uses around half the space of the blockchain with rocksdb engine, and about the same space with myisam. I consider that a win, though it's not suitable for all uses. 

Anyway, I'm open to ideas about what you had in mind. I'm only one guy putting in occasional efforts.  

**edit:** It just occurred to me that it may be quite easy to add a ORM layer as an api module similar to the Insight or BCI ones. These modules are now loadable by config setting. Instead of one providing a JSON based web api backend it could provide an interface to some ORM system. Seems doable but I have not given it more thought yet. I don't personally have the need. If there was a project that really could use that and I became interested then it could be done. Or someone else could do that and maintain that module.
