### ISSUE TITLE
Address ID collisions

### ISSUE THREAD

**Issue by jeanmonet** [neocogent/sqlchain#8]
Hi,

I was playing with your sqlchain app (thank you for your development) and noticed, while testing some of its features, that I could find collisions for the "id" of a given address.

Meaning that the same "id" can be shared by more than one addresses. Worth noting for readers that the "address" SQL table stores 2 values: "id" (a hash of the address) and "addr" (which is unhexed RipeMD format of the address).

I stumbled upon a few cases where, for a given valid address, I would find the corresponding "id" (using the hashing your propose in your script) and that "id" would correspond to a different address in the "address" table. I tested and both addresses hash to the same "id" => collision.

Since the SQL table has a "unique" constraint on the "id" of an address, I was wondering if you were aware of this feature (meaning the existence of "id" collisions for multiple addresses) and if you had any thoughts?

Thanks

Adding further details: when doing a sha256 of the 2 concerned addresses (RipeMD) -> the first 5 bytes (of 32 total) of the sha256 results are identical. The addr2id function uses those first 5 bytes to create an id. Thus the same id results for 2 different addresses. Note that I found quite a few such "collisions".

**Comment by neocogent** [comment]
This is known and accounted for in the table insertion code, `insertAddress` util.py line 334.

Insertion always checks for existence and increments the ID until an unused one is found. It is consistent only within the DB so the `addr2id` should not be used as a universal / external mapping scheme. The same is also used for tx ID columns, code immediately after above function. 

I knew this was perhaps less than ideal but it was important in trying to reduce the DB and index size overall. It does make a significant difference and adds very little overhead to addr/tx insertion times. Index size is important for not just disk size but in-memory tables where density affects lookup speed.

Also, when `addr2id` is called with a db cursor it will lookup the ID and return an adjusted ID that matches an inserted one. Hopefully I haven't slipped up and only use this version when doing db queries. 

Note that with tx ID when a collision exceeds a set limit (warn=32 by default) a log msg is emitted. I have done searches on the logs even after full syncs to see if that happens and so far I've never found one exceeding 32. My recollection (somewhat fading) from early testing with debug info (since removed) was that I never saw more than 6-7 consecutive collisions and they were very rare. Single collisions are quite common though but it was worth the space savings since my initial goal was making the SQL data as compact as possible. It's part of the reason the SQL tables are not 5x the size of the blockchain as in some other explorers.

Hope that helps.

**Comment by jeanmonet** [comment]
Thank you for your detailed reply, it is indeed very helpful to understand the logic behind that choice and the workaround.

Incidentally, I was curios if you intend to upgrade the sqlchain code to Python 3?
Also, this is off-topic, but I got stuck in the sync process at February 2017 (where speed slows at 5-10tx/s) on a 16GB RAM config with HDD (also upgraded to MySQL 8 which seems to have cut 20% off performance). From your experience, would an SSD drastically change the sync speed?

Thanks again for your feedback !

**Comment by neocogent** [comment]
I'd really like to upgrade to Python 3. I just haven't had the time/incentive to work on that. But if I continue with the project then it has to be on the roadmap. Also adding Postgresql support.

An SSD is essential to syncing in my experience. The further along you go the more it becomes mandatory. I'm a bit surprised you got that far on a hard disk. Back a few years when I started I think I gave up at even a lower block that that. It gets very slow on hard disk due to index insertions and tree re-orgs. 

Another option that helps a fair bit (but only with SSD) is to use MariaDB with RocksDB engine. The main issue is that index keys are hashes and so random data. This means index re-orgs are triggered a lot. The RocksDB engine is claimed to be better at random keys. In my testing it was not faster at low block count but as the indexs grow huge it becomes more efficient and does help. It's also much more compact than MyISAM or InnoDB. Even so, with RocksDB on a dedicated box it took 7 days to sync to around Feb.2018 (last time I recall doing full sync). 

If you want to read a bit more info about my early dev work and testing I have a [blog](https://www.neocogent.com) that is mostly about this project and a few other btc related things. It's very sporadic but does cover some things I figured out a long the way. In particular [about SSD](https://www.neocogent.com/blog/2017/01/why-you-want-ssd.html) performance.

**Comment by jeanmonet** [comment]
I'm not a professional programmer, but I would enjoy helping to upgrade this app to Python 3 during some of my free time. I was also going to ask if you thought of integrating SQLAlchemy which would give some flexibility in DB choice (such as MySQL/PostgreSQL)?

Thank you for your tips, I did read some of those posts in the past but probably missed the SSD one you just highlighted!
