### ISSUE TITLE
Sitrep

### ISSUE THREAD

**Issue by j1warren** [neocogent/sqlchain#9]
Hi, @neocogent
Thank you for this awesome app!
I want to report that it successfully works with the latest 0.20 bitcoind and with no-sigs it uses 120GB.
```
15G	sqlchain_bitcoin
105G	/var/lib/mysql/#rocksdb/
```

Sometimes I'm having troubles when with locks on start (mostly). Is there anything to be done?

```Traceback (most recent call last):
  File "/usr/local/bin/sqlchaind", line 475, in <module>
    run()
  File "/usr/local/bin/sqlchaind", line 442, in run
    blksdone = getBlocks(sqc.cfg['block'] if 'block' in sqc.cfg else 0)
  File "/usr/local/bin/sqlchaind", line 70, in getBlocks
    checkMemPool(cur)
  File "/usr/local/bin/sqlchaind", line 239, in checkMemPool
    cur.execute("delete from mempool;")
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (1205, 'Lock wait timeout exceeded; try restarting transaction')

  File "/usr/local/bin/sqlchaind", line 198, in BlockHandler
    insertBlock(cur, blockQ.get(True, 5))
  File "/usr/local/bin/sqlchaind", line 350, in insertBlock
    cur.execute("delete from mempool where id=%s limit 1;", (tx_id,))
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1205, 'Lock wait timeout exceeded; try restarting transaction')

  File "/usr/local/bin/sqlchaind", line 198, in BlockHandler
    insertBlock(cur, blockQ.get(True, 5))
  File "/usr/local/bin/sqlchaind", line 350, in insertBlock
    cur.execute("delete from mempool where id=%s limit 1;", (tx_id,))
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction (snapshot conflict)')

```

Also, when the DB sync is finished sqlchaind often stops processing new blocks.
I see getBlocks() finding new blocks correctly, but BlockHandler thread doesn't process them somehow and it hangs like this
> Block 634033 [ Q:0 2915 txs - 10-06-2020 - 395ms 0.5s 5800 tx/s]

Also, api daemon loves to tell this and then needs restart.
```
 do_API
    result = json.dumps(apiBlock(cur, args[1]))
  File "/usr/local/lib/python2.7/dist-packages/sqlchain/insight.py", line 88, in apiBlock
    cur.execute("select id,chainwork,blksize from blocks where hash=%s limit 1;", (blkhash.decode('hex')[::-1],))
  File "/usr/local/lib/python2.7/dist-packages/sqlchain/dbpool.py", line 145, in execute
    return self.conn.apply(self.cursor.execute,*args)
  File "/usr/local/lib/python2.7/dist-packages/sqlchain/dbpool.py", line 122, in apply
    return self.conn_.apply(function,*args)
  File "/usr/local/lib/python2.7/dist-packages/sqlchain/dbpool.py", line 113, in apply
    raise self.state.error
OperationalError: (2006, 'MySQL server has gone away')
2020-06-10T13:24:43Z {'REMOTE_PORT': '52064', 'HTTP_HOST': 'localhost:8085', 'REMOTE_ADDR': '127.0.0.1', (hidden keys: 25)} failed with OperationalError
```

PS initcfg() creates config with Yes/No values, had to change them to true/false.

**Comment by neocogent** [comment]
Thanks for your report. Glad to hear someone is using it. I rarely ever hear anything from anyone and it has been a couple years since I have run or even looked at the code, so my head is not in the right space to dig in and fix things. I can try a couple suggestions.

The checkMemPool() code only runs when it is in polling mode. Even when I last ran it I hardly used that mode as I was focused on getting ZMQ to work. I guess you don't have ZMQ configured on bitcoind and I'd suggest doing that as it is far more efficient and hopefully runs better. Rather than polling bitcoind and comparing mempool data it simply uses ZMQ messages to update it's  mempool. I'm guessing there is a situation during mempool checking that deadlocks and I never caught it because I had moved on to always using ZMQ. That also may have some bearing on it not transitioning from "initial-sync" mode to normal mode when the DB nears full sync. That's another changeover that was altered when I added ZMQ support and I never went back and re-checked it when not using ZMQ. To configure ZMQ it's only a couple lines in bitcoin.conf and I think a setting in the sqlchain.cfg  (a bit fuzzy for me now...). 

The "OperationalError: (2006, 'MySQL server has gone away')" error is something I do recall seeing and if I recall I fixed for myself by increasing some timeout values in MySQL settings. I think I did some googling on that error and tried some fairly generic suggestions. Unfortunately I don't now recall specifics. It was perhaps connection or r/w timeouts? I do recall having the issue and fixing it without code changes. I should have documented it - or maybe I did but have forgotten, so check my install doc notes just in case.

The initcfg() problem I'm a bit baffled by. I think the Yes/No values should be converted to 1/0 values for actual cfg written. Perhaps I missed that in some values and it never got caught in my testing? If you can let me know exactly which ones wrote out Yes/No in actual config or what exactly happened that you fixed then I'll see if I can update it. Or, if you are sure your changes fix it then just submit a fix as pull request. I don't have a running copy now and won't be able to test changes in the near future due to other work, but if I can see that it looks correct I'll update it.

If I were to come back to this code and update the project I'd likely want to update it all to Python 3 and replace the config program with a web panel for setup and monitoring. However, I don't expect to do that any time soon. It's nice to know it's working up to block 634,033. That's cool.

Note also, there is potentially a vulnerability in very old jQuery code included in the demo page. So if you are doing any web based app using sqlchain-api I'd definitely suggest updating jQuery to a new version (> 3.50).

edit - here's example conf lines for enabling zmq:

bitcoin.conf
```
zmqpubrawtx=tcp://127.0.0.1:8432
zmqpubrawblock=tcp://127.0.0.1:8432
```
sqlchain.bitcoin.cfg
`"zmq": "tcp://127.0.0.1:8432"`

I googled the "mysql operational error 2006" and I believe the fix is to set the "wait_timeout = 28800", though possibly there was other values as this seems to be default now. Add that to mysql conf or use set global in mysql console.
